
config globals
	option workgroup 'WORKGROUP'
	option description 'Ksmbd on OpenWrt'
	option interface 'lan loopback'

config share
	option name 'TerryzaCloud'
	option path '/mnt/terryza-cloud/cloud'
	option read_only 'no'
	option guest_ok 'no'
	option users 'ram2'
	option create_mask '0664'
	option dir_mask '0775'
	option force_root '1'
