
config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd1e:38f7:5fbc::/48'

config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'eth0'

config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'

config interface 'wan'
	option device 'usb0'
	option proto 'dhcp'

config interface 'wan6'
	option device 'usb0'
	option proto 'dhcpv6'
	option reqprefix 'auto'

config interface 'wg0'
	option proto 'wireguard'
	option listen_port '51820'
	list addresses '10.77.0.1/24'

config wireguard_wg0
	option description 'SamsungPhone'
	option public_key '1KfkoEiBCn6K0gYHUYGr4qseWgiMJLuo6dlRYPAe2RQ='
	list allowed_ips '10.77.0.2/32'
	option route_allowed_ips '1'

config interface 'tailscale'
	option proto 'none'
	option device 'tailscale0'

